### ISSUE TITLE
Proposal to add built-in operator redefines

### ISSUE THREAD

**Issue by zillou** [ericmj/decimal#145]
When doing mathematical operations on Decimal data, I feel `Decimal.add(a, b)` is harder to read than the form of `a + b`. 

The latter format can be achieved through [Redefining existing operators](  https://hexdocs.pm/elixir/master/operators.html#redefining-existing-operators)
I did a little experiment about the solution and came up a working snippet listed below.

My questions are:

1. Is there any potential issue with this solution?
2. Is it worth to extend this and include it in Decimal package? 

----

```elixir
defmodule Decimal.OperatorOverride do
  def left + right do
    case {left, right} do
      {%Decimal{}, %Decimal{}} ->
        Decimal.add(left, right)
      _ ->
        :erlang.+(left, right)
    end
  end

  defmacro __using__(_opts) do
    quote do
      import Kernel, except: [+: 2]
      import Decimal.OperatorOverride
    end
  end
end
```

Usage:

```
iex(1)> use Decimal.OperatorOverride
Decimal.OperatorOverride
iex(2)> Decimal.new(1) + Decimal.new(2)
#Decimal<3>
iex(3)> 1 + 2
3
```

**Comment by ericmj** [comment]
The main issue with this change is that the numeric operators become slower and that they will no longer work in guards. Since that's fairly major I wouldn't want to change the operators globally with `use Decimal.OperatorOverride`.

One solution could be to only change them within a specific scope, for example:

```elixir
Decimal.with_operators do
  Decimal.new(1) + Decimal.new(2)
end
```

**Comment by wojtekmach** [comment]
Agreed with above, I actually have a proof of concept for that here: https://github.com/wojtekmach/decimal_eval/blob/master/lib/decimal_eval.ex.

Thinking about it more, I'm not sure about semantics, currently it works like this:

```elixir
iex> DecimalEval.eval 1 + 0
#Decimal<1>

iex> DecimalEval.eval 1
1
```

since `DecimalEval.eval` it's a macro we could rewrite all numbers to be decimals which should be fine because again we're doing that in a very narrow scope but feels potentially dangerous, not sure.

**Comment by zillou** [comment]
Thank you for your explain and the better solution. I really like the idea to make the scope as narrow as possible.

**Comment by tomekowal** [comment]
Great idea!

I would appreciate a macro like that, but I think it should work only on basic operations. E.g.

```elixir
def my_sum(a, b) do
  a + b
end

Decima.eval my_sum(a, b)
```

should crash. Otherwise, it gives false impressions that it works for everything.

E.g. function

```elixir
def add_n_times(0, number), do: number
def add_n_times(n, number), do: add_n_times(n-1, number+number)
```

would need to have the first argument as a regular integer, and second converted to Decimal. That is too complicated.

I prefer the macro works only on basic operations and variables like:

```
b = 1
Decimal.eval 1 + 2 / b
```

**Comment by ericmj** [comment]
That's great because we can't make it work for `Decimal.eval my_sum(a, b)` :).

**Comment by wojtekmach** [comment]
If we were to do it, initially I was skeptical about constraining it that e.g. my_sum(a, b) wouldn't even be allowed, I thought leaving a disclaimer along the lines of: if you're using functions in eval, make sure they work on decimals. For example, there's no reason why we shouldn't allow calling Kernel.if inside. 

But I think I agree with constraining it, e.g. someone could do: `eval min(a, b) * a` and it would give the wrong result! (`Kernel.min` does structural comparison.) and so the only sane way seems to be explicitly list what's allowed.

**Comment by kipcole9** [comment]
> iex> DecimalEval.eval 1
1

What would `DecimalEval.eval 1.246` return? Given that `Decimal.new/1` doesn't support floats would it check at compile time that its a float constant and use `Decimal.from_float/1`?

I have a number of library functions I've written over the years that take `Decimal`, `Float` and `Integer` arguments mixed where that is semantically appropriate. Then there is also the @qqwy's library [for rational numbers](https://hex.pm/packages/ratio). And some derivative libraries like my [money](https://hex.pm/packages/ex_money) that delegates to `Decimal` for math operations but is its own struct. 

1. I would like a more general solution for a math operator protocol or `eval` function but to @ericmj 's point, if its a protocol then it will slow things down. I think there are already a couple of implementations in the wild and I suppose if they were scoped locally enough it would have minimal impact - but the language doesn't really make it easy to determine at compile time the type of the arguments with 100% certainty.

2. `Decimal.eval/1` per @wojtekmach's example looks good. But then its starts to get a bit more like a DSL with caveats and limitations. Is that better than the explicit function calls (although they do get unwieldy if there are more than two operands).

**Comment by Qqwy** [comment]
Thanks for referring to one of my libraries, @kipcole9 !
This is a very interesting discussion.

I did some work in the past that is very much related to this, mostly because I wanted to be able to express algorithms that were generic across numeric types (regardless of whether that would be integers, floats, decimals, rationals, complex numbers, etc.) which resulted in the [Numbers](https://hexdocs.pm/numbers/Numbers.html) library, which is exactly a 'math operator protocol' library.

It allows you to use named functions (1:1 like Decimal's) across numeric datatypes, and allows you to use the inline operators as well _if you explicitly enable them_ (for exactly the issue that @ericmj outlined above: within guards they will still only work on integers/floats).

---

Personally I currently am of the opinion that adding a lot of bells and whistles to libraries that are used very widely in the Elixir ecosystem like Decimal might not be the best idea. Rather, I think it makes more sense if these libraries are small and stable, so that other libraries (of which there could be many, with many different ideas and approaches) can all agree on the same underlying data type(s) and interface surface(s).

**Comment by wojtekmach** [comment]
> Decimal.eval/1 per wojtekmach's example looks good. But then its starts to get a bit more like a DSL with caveats and limitations. Is that better than the explicit function calls

> Personally I currently am of the opinion that adding a lot of bells and whistles to libraries that are used very widely in the Elixir ecosystem like Decimal might not be the best idea.

I think both are excellent points 👍

**Comment by Bumppoman** [comment]
> The main issue with this change is that the numeric operators become slower and that **they will no longer work in guards**. Since that's fairly major I wouldn't want to change the operators globally with `use Decimal.OperatorOverride`.
> 
> One solution could be to only change them within a specific scope, for example:
> 
> ```elixir
> Decimal.with_operators do
>   Decimal.new(1) + Decimal.new(2)
> end
> ```

What's the reason we wouldn't want to implement these as guards?  Seems possible now, especially in combination with the is_decimal/1 guard.

**Comment by ericmj** [comment]
It is not possible those operations as guards. Guards are very limited in the expression they allow.

**Comment by Bumppoman** [comment]
> It is not possible to implement those operations as guards. Guards are very limited in the expression they allow.

Sure, and in looking at the `Decimal.add` function at least, the only one that seems problematic is `Kernel.min`.  I doubt that would be insurmountable if one were sufficiently interested :). Guards have come a long way since early 2020, this might be worth revisiting!

**Comment by Qqwy** [comment]
If people want to use operators with Decimal right now, there are some libraries that allow it. Amongst them [numbers](https://github.com/Qqwy/elixir-number#overloaded-operators) (which I'm the author of), which overrides the builtin operators for the 'normal' context but still falls back to Elixir's normal implementations for the 'guard' context (so these still work).

@Bumppoman The main difficulty with implementing many of the `Decimal` operations in a guard-safe fashion is that there often needs to be some normalization or pattern matching (some kind of 'case statement' or 'if/else' at least) to properly deal with the various values stored in the Decimal structs. You cannot really do this in a single guard, and Elixir currently does not allow expanding a single guard clause into multiple during compilation.

If you want more information on the subject, I wrote a [blog post](https://medium.com/@W_Mcode/down-the-rabbit-hole-defining-a-guard-safe-modulo-operation-in-elixir-6335ade7c078) about adding a guard-safe modulo some years back, and this was also the subject of my [Code Beam V 2020 talk](https://www.youtube.com/watch?v=Mb1Wb3dZZ8U), which has some more general notes as well as doing some benchmarking of guards vs non-guards.

**Comment by Bumppoman** [comment]
@Qqwy Definitely adds come context...thanks for the reading material!

**Comment by ericmj** [comment]
> Guards have come a long way since early 2020, this might be worth revisiting!

As far a I know nothing has happened with the underlying functionality of guards for a long time. Among other things you need pattern matching and recursion to implement the operators which simply don't exist in guards.

If it was possible to have the operators work in guards then we would probably make them work in guards, but unfortunately it's not possible without fundamental changes to Erlang which are likely not happening any time soon.
