### ISSUE TITLE
Error when using floats in Decimal.div?

### ISSUE THREAD

**Issue by mnussbaumer** [ericmj/decimal#89]
Hey,
I've ran into this:

iex(34)> Decimal.div(Decimal.new(023), Decimal.new(0.00023))
#Decimal<1E+5>
iex(35)> Decimal.div(023, 0.00023)                          
** (ArgumentError) cannot automatically convert 2.3e-4 to Decimal
    (decimal) lib/decimal.ex:1639: Decimal.decimal/1
    (decimal) lib/decimal.ex:488: Decimal.div/2

Is there a reason why the divisor throws in this case instead of converting the value?
(actually it's whenever there's a float in the parameters)

**Comment by wojtekmach** [comment]
@mnussbaumer we want to discourage users from using floats directly because of things like:

```
iex(2)> Decimal.new(1.01 + 1.02)
#Decimal<2.0300000000000002>
```

so it would be all to easy to run into e.g.: `Decimal.add(0, 1.01 + 1.02)` and end up with a result that wasn't intentional. For this reason, in arithmetic operations we only allow passing decimals as well as integers and strings which can be safely converted to decimals.

Moreover, we have soft deprecated (no warning yet) passing floats to `Decimal.new` and instead added `Decimal.from_float` function. Passing floats to `Decimal.new` will be deprecated in next release and eventually removed.

I think the error message could be improved, I'll look into it.

**Comment by mnussbaumer** [comment]
@wojtekmach thank you for the response, it makes sense then, I wouldn't expect 1.01+1.02 to yield 2.03.......2. Closing
